# Generated by Django 2.2 on 2020-06-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theVault', '0003_newnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='newnote',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
