# Generated by Django 2.2 on 2020-08-09 22:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theVault', '0004_newnote_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newnote',
            name='pershkrimi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Content'),
        ),
    ]
